version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-btp
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: btp_tokens
    ports:
      - "5432:5432"
    volumes:
      - ./internal/pkg/db/init:/docker-entrypoint-initdb.d
